source 'http://rubygems.org'

gem 'sinatra', '~> 2.0', '>= 2.0.2'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem	'require_all'
gem 'pry'
gem 'shotgun'
gem 'bcrypt'
gem 'thin'
gem 'sqlite3'
gem 'sinatra-flash', '~> 0.3.0'